spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Simon!!2019
    url: jdbc:mysql://localhost:3306/biyin_hk?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true